#!/usr/bin/env python3
"""tti2h.py — convert an MRG .tti teletext page into a C header for Cathode Ray.

Usage:  python3 tti2h.py input.tti > ttx_page.h

Parses the minimal command set needed for a single static page:
  PN,<page><subpage>   page number (first 3 hex/dec digits) + subpage
  OL,<row>,<data>      output line: 40 teletext bytes for the given row

OL data decode (authoritative, matches vbit2 TTXLine):
  - 0x1B (ESC): take the NEXT char & 0x3F  -> control code 0x00..0x1F
  - char < 0x20: end of line
  - else: char & 0x7F
  Result padded/truncated to exactly 40 bytes, padding = 0x20 (space).

Output: const uint8_t ttx_page[TTX_ROWS][40] of 7-bit codes (NO parity — the
firmware adds odd parity at transmit time), plus TTX_PAGE / TTX_MAGAZINE.
"""
import sys


def decode_ol(data: bytes) -> list:
    out = []
    i = 0
    while i < len(data) and len(out) < 40:
        b = data[i]
        if b == 0x1B:                 # ESC -> control code in next byte
            i += 1
            if i >= len(data):
                break
            out.append(data[i] & 0x3F)
        elif b < 0x20:                # raw control byte = end of line
            break
        else:
            out.append(b & 0x7F)
        i += 1
    while len(out) < 40:
        out.append(0x20)              # pad with spaces
    return out[:40]


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: tti2h.py input.tti > ttx_page.h\n")
        sys.exit(1)

    rows = {}              # row number -> list[40]
    page = 0x100
    magazine = 1

    with open(sys.argv[1], "rb") as f:
        for raw in f.read().split(b"\n"):
            raw = raw.rstrip(b"\r")
            if raw.startswith(b"PN,"):
                # PN,<digits>  e.g. 1007F -> page 100, subpage 7F
                val = raw[3:].strip()
                try:
                    pagenum = int(val[:3], 16)   # first 3 hex digits = mmm page
                    page = pagenum
                    magazine = (pagenum >> 8) & 0x7  # hundreds digit -> magazine
                    if magazine == 0:
                        magazine = 8
                except ValueError:
                    pass
            elif raw.startswith(b"OL,"):
                # OL,<row>,<data>
                rest = raw[3:]
                comma = rest.find(b",")
                if comma < 0:
                    continue
                try:
                    rownum = int(rest[:comma])
                except ValueError:
                    continue
                rows[rownum] = decode_ol(rest[comma + 1:])

    max_row = max(rows) if rows else 0
    n_rows = max_row + 1   # include row 0 slot (header built by firmware)

    w = sys.stdout.write
    w("// Auto-generated by tools/tti2h.py - do not edit.\n")
    w("// Teletext page data: 7-bit codes, pre-parity (firmware adds odd parity).\n")
    w("#pragma once\n#include <cstdint>\n\n")
    w(f"#define TTX_PAGE      0x{page:03X}\n")
    w(f"#define TTX_MAGAZINE  {magazine}\n")
    w(f"#define TTX_ROWS      {n_rows}   // rows 0..{max_row}; row 0 = header\n\n")
    w("static const uint8_t ttx_page[TTX_ROWS][40] = {\n")
    for r in range(n_rows):
        data = rows.get(r, [0x20] * 40)
        body = ",".join(f"0x{b:02X}" for b in data)
        w(f"    {{ {body} }},  // row {r}\n")
    w("};\n")


if __name__ == "__main__":
    main()
